//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatEmcriptacion
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class mensajeria
    {
        public int idmensaje { get; set; }
        public int idemisor { get; set; }
        public string mensaje { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }

        [JsonIgnore]
        public virtual usuario usuario { get; set; }
    }
}
